#!/bin/bash

function do_cmd {
    echo $@
    $@
    
    if [ "$?" -ne "0" ]; then
        echo "*** ERROR ***"
        exit
    fi
}

# Clear the screen
/usr/bin/osascript -e 'tell application "System Events" to tell process "Terminal" to keystroke "k" using command down'

# Any argument triggers skipping of actual build step (only do the copying)
if [ -z $1 ]; then
    # Build and reobfuscate
    do_cmd cd ~/work/forge/mcp
    do_cmd ./recompile.sh
    do_cmd ./reobfuscate.sh
fi

# Make the zip file
do_cmd cd ~/work/forge/mcp/reobf/minecraft/
do_cmd zip -r weirdBlock.zip pdunham

# Copy the mod to the client and server
do_cmd cp weirdBlock.zip ~/ftb/YogCraft/minecraft/mods/
do_cmd cp weirdBlock.zip ~/Desktop/MineCraft/FeedTheBeast/MindCrack/minecraft/mods/
do_cmd cp weirdBlock.zip ~/Desktop/MineCraft/ftb_server/mods/
do_cmd cp weirdBlock.zip ~/Desktop

# Copy the mod to Ian's machine
# do_cmd rm /Volumes/Users/Ian/Desktop/FTB/Direwolf20/minecraft/mods/weirdBlock.zip
# do_cmd cp weirdBlock.zip /Volumes/Users/Ian/Desktop/FTB/Direwolf20/minecraft/mods 
# # Copying files w/ spaces is messed up
# set "weirdBlock.zip" "/Volumes/Users/Ian/Documents/Game Folders/Minecraft/Yogcraft server FTB/mods/"
# echo cp $@
# rm "$@"
# cp "$@weirdBlock.zip"
# 
echo "Successs"
echo